FROM debian:jessie-slim
RUN apt-get update
RUN apt-get -y install iptables apt-utils iproute2 net-tools systemd telnet nano iputils-ping tcpdump inetutils-traceroute quagga bind9
RUN apt-get -f install
COPY ./quagga /etc/quagga
COPY named.conf /etc/bind
COPY named.conf.options /etc/bind
RUN mkdir /etc/bind/zones
COPY ./zones/groupe2.db /etc/bind/zones
COPY serveurDNS.sh /home/
RUN ["chmod", "+x", "/home/serveurDNS.sh"]
RUN mkdir /etc/scripts
ENV PATH "/etc/scripts:$PATH"
ENTRYPOINT /etc/init.d/quagga start && /bin/bash